### ISSUE TITLE
xxl-job调度任务成功，但回调时会重定向到登录，导致解析问题

### ISSUE THREAD

**Issue by Ian-zy1** [fcfangcc/pyxxl#52]
**Problem description**

xxl-job调度任务成功，但回调时重定向到xxl登录。xxl_client.XXL.callback() 方法尝试从服务器获取JSON数据，但服务器返回了HTML内容（text/html;charset=utf-8），这与预期不符，导致了解析失败。

**Steps to reproduce the problem**

```python
config = ExecutorConfig(
    xxl_admin_baseurl="http://localhost:20052/xxl-job-admin/api/",
    executor_app_name="ftp-server",
    executor_host="10.1.1.1",
    executor_port=9992,
    access_token='xxl-job',
    debug=True,
)
app = PyxxlRunner(config)


@app.register(name="pushProjectBusinessDataToFtp")
def test_task():
    # you can get task params with "g"
    g.logger.info("get executor params: %s" % g.xxl_run_data.executorParams)
    for i in range(10):
        g.logger.warning("test logger %s" % i)

    return "success 12300"


if __name__ == "__main__":
    app.run_executor()
```

**Specifications like the version of the project, operating system, or hardware**

* XXL-JOB 版本: 2.3.0
* pyxxl 版本: 0.3.6
* python 版本: python3.12
* other more:

**Comment by fcfangcc** [comment]
日志里面有具体的失败原因的，看下或者贴出来。还有把issue的信息补全下，不然不好排查

**Comment by Ian-zy1** [comment]
2024-08-19 09:45:52.777 [MainThread] [NotInTask] DEBUG /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/setting.py(__post_init__:103) - init config: {'xxl_admin_baseurl': 'http://10.3.240.112:20052/xxl-job-admin/api/', 'executor_app_name': 'ftp-server', 'access_token': 'xxl_job', 'executor_log_path': 'pyxxl.log', 'executor_port': 9999, 'executor_host': '10.1.140.27', 'executor_listen_port': 9999, 'executor_listen_host': '0.0.0.0', 'max_workers': 30, 'task_timeout': 600, 'task_queue_length': 30, 'graceful_close': False, 'graceful_timeout': 300, 'log_target': 'disk', 'log_local_dir': 'logs', 'log_redis_uri': '', 'log_expired_days': 14, 'dotenv_try': True, 'dotenv_path': None, 'debug': True}
/dev/project/python/hongxin/tianjin_custom/project_business/impl/push_project_business_to_ftp.py:387: SyntaxWarning: Using the sync method will unknown blocking exception, consider using async method.
  @app.register(name="pushProjectBusinessDataToFtp")
2024-08-19 09:45:52.778 [MainThread] [NotInTask] DEBUG /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py(func_wrapper:92) - register job pushProjectBusinessDataToFtp,is async: False
2024-08-19 09:45:52.779 [MainThread] [NotInTask] INFO /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/main.py(_cleanup_ctx:107) - register with handlers ['<pushProjectBusinessDataToFtp is_async:False>']
2024-08-19 09:45:52.779 [MainThread] [NotInTask] INFO /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/main.py(server_info_ctx:31) - start executor server with pid 6099.
2024-08-19 09:45:52.779 [MainThread] [NotInTask] DEBUG /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/logger/common.py(expired_loop:45) - start expired_loop...
2024-08-19 09:45:52.779 [MainThread] [NotInTask] DEBUG /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py(_post:87) - post to xxl-job path=registry payload={'registryGroup': 'EXECUTOR', 'registryKey': 'ftp-server', 'registryValue': 'http://10.1.140.27:9999'}
2024-08-19 09:45:52.786 [MainThread] [NotInTask] WARNING /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/main.py(_register_task:76) - Register task is exit.
2024-08-19 09:45:59.984 [MainThread] [NotInTask] INFO /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/server.py(run:54) - Get task request. jobId=183 logId=434891 [RunData(jobId=183, logId=434891, executorHandler='pushProjectBusinessDataToFtp', executorBlockStrategy='SERIAL_EXECUTION', executorParams='', executorTimeout=0, logDateTime=1724031960002, glueType='BEAN', glueSource='', glueUpdatetime=1723716513000, broadcastIndex=0, broadcastTotal=1)]
2024-08-19 09:45:59,985 - aiohttp.access - INFO - 10.3.240.112 [19/Aug/2024:09:45:59 +0800] "POST /run HTTP/1.1" 200 190 "-" "Java/1.8.0_241"
2024-08-19 09:45:59.986 [MainThread] [434891] INFO /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py(_run:224) - Start job jobId=183 logId=434891 [RunData(jobId=183, logId=434891, executorHandler='pushProjectBusinessDataToFtp', executorBlockStrategy='SERIAL_EXECUTION', executorParams='', executorTimeout=0, logDateTime=1724031960002, glueType='BEAN', glueSource='', glueUpdatetime=1723716513000, broadcastIndex=0, broadcastTotal=1)]
2024-08-19 09:46:00,023 - root - INFO - 需要上报的项目数量: 20
2024-08-19 09:46:10,528 - root - INFO - 文件 proj_20240819.txt 上传成功
2024-08-19 09:46:10,529 - root - INFO - 项目及业务数据推送到综调FTP任务执行完成，耗时: 10.54s
2024-08-19 09:46:10.530 [MainThread] [434891] INFO /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py(_run:227) - Job finished jobId=183 logId=434891
2024-08-19 09:46:10.530 [MainThread] [434891] DEBUG /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py(_post:87) - post to xxl-job path=callback payload=[{'logId': 434891, 'logDateTim': 1724031959986, 'handleCode': 200, 'handleMsg': None, 'executeResult': {'code': 200, 'msg': None}}]
2024-08-19 09:46:10.542 [MainThread] [434891] ERROR /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py(_run:241) - 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url='http://10.3.240.112:20052/toLogin'
Traceback (most recent call last):
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py", line 228, in _run
    await self.xxl_client.callback(data.logId, start_time, code=200, msg=result)
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py", line 83, in callback
    await self._post("callback", payload)
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py", line 94, in _post
    r = Response(**(await response.json()))
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/venv/my_venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url='http://10.3.240.112:20052/toLogin'
2024-08-19 09:46:10.546 [MainThread] [434891] DEBUG /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py(_post:87) - post to xxl-job path=callback payload=[{'logId': 434891, 'logDateTim': 1724031959986, 'handleCode': 500, 'handleMsg': "0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url='http://10.3.240.112:20052/toLogin'", 'executeResult': {'code': 500, 'msg': "0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url='http://10.3.240.112:20052/toLogin'"}}]
2024-08-19 09:46:10.553 [MainThread] [434891] INFO /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py(_finish:254) - Finish task <XXLTask task=<Task pending name='Task-10' coro=<Executor._run() running at /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py:249>> data=RunData(jobId=183, logId=434891, executorHandler='pushProjectBusinessDataToFtp', executorBlockStrategy='SERIAL_EXECUTION', executorParams='', executorTimeout=0, logDateTime=1724031960002, glueType='BEAN', glueSource='', glueUpdatetime=1723716513000, broadcastIndex=0, broadcastTotal=1)>
2024-08-19 09:46:10,554 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Executor._run() done, defined at /dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py:217> exception=ContentTypeError(RequestInfo(url=URL('http://10.3.240.112:20052/toLogin'), method='GET', headers=<CIMultiDictProxy('Host': '10.3.240.112:20052', 'XXL-JOB-ACCESS-TOKEN': 'xxl_job', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.12 aiohttp/3.10.3')>, real_url=URL('http://10.3.240.112:20052/toLogin')), (<ClientResponse(http://10.3.240.112:20052/xxl-job-admin/api/callback) [302 None]>
<CIMultiDictProxy('Location': '/toLogin', 'Content-Length': '0', 'Date': 'Mon, 19 Aug 2024 01:46:10 GMT')>
,), message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', headers=<CIMultiDictProxy('Content-Type': 'text/html;charset=UTF-8', 'Content-Language': 'en-US', 'Transfer-Encoding': 'chunked', 'Date': 'Mon, 19 Aug 2024 01:46:10 GMT')>)>
Traceback (most recent call last):
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py", line 228, in _run
    await self.xxl_client.callback(data.logId, start_time, code=200, msg=result)
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py", line 83, in callback
    await self._post("callback", payload)
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py", line 94, in _post
    r = Response(**(await response.json()))
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/venv/my_venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url='http://10.3.240.112:20052/toLogin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/executor.py", line 242, in _run
    await self.xxl_client.callback(data.logId, start_time, code=500, msg=str(err))
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py", line 83, in callback
    await self._post("callback", payload)
  File "/dev/venv/my_venv/lib/python3.12/site-packages/pyxxl/xxl_client.py", line 94, in _post
    r = Response(**(await response.json()))
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/dev/venv/my_venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url='http://10.3.240.112:20052/toLogin'

**Comment by fcfangcc** [comment]
pyxxl访问`http://10.3.240.112:20052/xxl-job-admin/api/callback`然后被服务端重定向到`http://10.3.240.112:20052/toLogin'`了。服务端忘这个方向排查吧，看看为什么被重定向了

**Comment by studyletmehappy1** [comment]
同蹲，解决方法

**Comment by Ian-zy1** [comment]
> 同蹲，解决方法

1.检查你所使用的xxl-job-admin的配置，查看是否配置了上下文路径，即

**Comment by studyletmehappy1** [comment]
感谢❀
